# Generated by Django 4.2a1 on 2023-02-17 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='null')),
                ('looking', models.TextField(default='null')),
                ('problems', models.TextField(default='null')),
                ('products', models.TextField(default='null')),
                ('speaking_brand', models.TextField(default='null')),
                ('buy_before', models.CharField(default='null', max_length=200)),
                ('rating_feedback', models.IntegerField(default=0)),
                ('sharing_probabilite', models.IntegerField(default=0)),
                ('user_age', models.IntegerField(default=24)),
                ('user_country', models.CharField(blank=True, default='egypt', max_length=150, null=True)),
                ('user_city', models.CharField(blank=True, default='city', max_length=150, null=True)),
                ('user_gender', models.CharField(blank=True, default='Male', max_length=150, null=True)),
                ('sent_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='null')),
                ('hear_brand', models.TextField(default='null')),
                ('see_brand', models.TextField(default='null')),
                ('speaking_brand', models.TextField(default='null')),
                ('buy_before', models.CharField(default='null', max_length=200)),
                ('use_before', models.CharField(default='null', max_length=200)),
                ('rating_experience', models.IntegerField(default=0)),
                ('rating_feedback', models.IntegerField(default=0)),
                ('sharing_probabilite', models.IntegerField(default=0)),
                ('other_brand', models.CharField(default='null', max_length=200)),
                ('best_brand', models.CharField(default='null', max_length=200)),
                ('user_age', models.IntegerField(default=24)),
                ('user_country', models.CharField(blank=True, default='egypt', max_length=150, null=True)),
                ('user_city', models.CharField(blank=True, default='city', max_length=150, null=True)),
                ('user_gender', models.CharField(blank=True, default='Male', max_length=150, null=True)),
                ('sent_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
